#!/usr/bin/env node
// ---------------------------------------------------------------------------
// AdoptOps parallel worktrees.
//
// One git worktree per workstream (git-workflow.md), each with its own
// branch, its own sqlite database, its own dev-server ports and its own
// .claude/launch.json, so several Claude Code sessions (or people) build,
// test and preview in parallel without stepping on each other.
//
//   node scripts/worktree.mjs add <workstream> <branch> [--link-modules] [--no-install]
//   node scripts/worktree.mjs next <workstream> <branch>      # re-point an existing worktree at a fresh branch from origin/main
//   node scripts/worktree.mjs sync [<workstream>]             # regenerate the CLAUDE.local.md session brief(s)
//   node scripts/worktree.mjs list
//   node scripts/worktree.mjs remove <workstream>
//
// Workstreams and their port slots (main checkout keeps 4104 / 5273):
//
//   overview    CAP 4114  client 5283   (journey pages, React)
//   scheduling  CAP 4124  client 5293   (tasks, adapters, ABAP mirror)
//   admin       CAP 4134  client 5303   (deploy, security, audit, CI, docs)
//   spare       CAP 4144  client 5313   (ad-hoc / review)
//
// Worktrees live beside the repository: <repo>.worktrees/<workstream>.
// Run this from the MAIN checkout (the one whose branch is `main`).
// ---------------------------------------------------------------------------

import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const SLOTS = {
  overview: { cap: 4114, client: 5283 },
  scheduling: { cap: 4124, client: 5293 },
  admin: { cap: 4134, client: 5303 },
  spare: { cap: 4144, client: 5313 }
};

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const worktreesRoot = `${repoRoot}.worktrees`;
const TAG = '[worktree]';

function log(message) { console.log(`${TAG} ${message}`); }
function fail(message) { console.error(`${TAG} ${message}`); process.exit(1); }

function git(args, options = {}) {
  const result = spawnSync('git', args, { cwd: options.cwd || repoRoot, encoding: 'utf8', stdio: options.inherit ? 'inherit' : 'pipe' });
  if (result.status !== 0 && !options.allowFailure) {
    fail(`git ${args.join(' ')} failed${result.stderr ? `:\n${result.stderr}` : ''}`);
  }
  return (result.stdout || '').trim();
}

function run(command, args, cwd, logFile, env = {}) {
  log(`${command} ${args.join(' ')}  (in ${path.relative(worktreesRoot, cwd) || cwd}, log: ${path.basename(logFile)})`);
  const out = fs.openSync(logFile, 'a');
  const result = spawnSync(command, args, { cwd, stdio: ['ignore', out, out], shell: true, env: { ...process.env, ...env } });
  fs.closeSync(out);
  if (result.status !== 0) fail(`${command} ${args.join(' ')} failed - see ${logFile}`);
}

function slotFor(workstream) {
  const slot = SLOTS[workstream];
  if (!slot) fail(`Unknown workstream "${workstream}". Use one of: ${Object.keys(SLOTS).join(', ')}`);
  return slot;
}

function worktreePath(workstream) {
  return path.join(worktreesRoot, workstream);
}

// .claude/launch.json is per-checkout (untracked). The with-env wrapper sets
// the slot's ports before npm runs the shared scripts, whose PORT?= defaults
// then yield. The CAP entry uses the no-watch script: `cds serve --watch`
// children on this machine stop serving HTTP after a reload (observed
// 2026-09-15), so restart the CAP preview by hand after backend changes.
function launchJson(slot) {
  return `${JSON.stringify({
    version: '0.0.1',
    configurations: [
      {
        name: 'adops-cap',
        runtimeExecutable: 'node',
        runtimeArgs: ['code/scripts/with-env.mjs', `PORT=${slot.cap}`, '--', 'npm', 'run', 'srv:sqlite:nowatch', '--prefix', 'code'],
        port: slot.cap
      },
      {
        name: 'adops-client',
        runtimeExecutable: 'node',
        runtimeArgs: ['code/scripts/with-env.mjs', `PORT=${slot.client}`, `VITE_ADOPS_CAP_SERVER=http://localhost:${slot.cap}`, '--', 'npm', 'run', 'dev', '--prefix', 'code/app/adops-client'],
        port: slot.client
      }
    ]
  }, null, 2)}\n`;
}

// Worktrees are always created from origin/main (fetched fresh), so the
// primary checkout may sit on any branch - it must only be the primary one,
// not itself a linked worktree.
// The per-worktree session brief. Claude Code reads CLAUDE.local.md (gitignored)
// next to CLAUDE.md at session start, so a session opened in a worktree knows
// its workstream, ports, branch and current item without a pasted prompt.
// Regenerated by add / next / sync; the "current item" is read from the
// workstream's tracker file at generation time and the brief tells the
// session to trust the tracker over this snapshot.
function inProgressItems(dir, workstream) {
  const tracker = path.join(dir, 'docu', '00-overview', 'tracker', `${workstream}.md`);
  if (!fs.existsSync(tracker)) return [];
  const lines = fs.readFileSync(tracker, 'utf8').split(/\r?\n/);
  const items = [];
  let inSection = false;
  for (const line of lines) {
    if (/^## /.test(line)) inSection = /^## in progress/i.test(line);
    else if (inSection) {
      const match = line.match(/^- \[~\] (.*)$/);
      if (match) items.push(match[1]);
    }
  }
  return items;
}

function sessionBrief(dir, workstream, branch, slot) {
  const items = inProgressItems(dir, workstream);
  const itemLines = items.length
    ? items.map((item) => `  - ${item}`).join('\n')
    : '  - (none marked) -> take the top To-do item of this workstream in roadmap order and mark it In progress before anything else';
  return `# Worktree session brief (${workstream})

Generated by \`node scripts/worktree.mjs\` on ${new Date().toISOString().slice(0, 10)}; do not edit by hand -
run \`node scripts/worktree.mjs sync\` to refresh. This file is gitignored and local to this worktree.

You are working in the **${workstream}** worktree at \`${dir}\` on branch \`${branch}\`.
Dev servers: CAP http://localhost:${slot.cap} (\`preview_start\` name \`adops-cap\`, no-watch script - restart it by
hand after backend changes), client http://localhost:${slot.client} (\`adops-client\`). Never start servers on 4104/5273
here; those belong to the primary checkout.

## Start of every session, before any other work

1. \`git branch --show-current\` must print \`${branch}\` (or the branch the tracker names). If it prints \`main\` or a
   detached HEAD, stop and ask - this worktree may need \`node scripts/worktree.mjs next ${workstream} <branch>\`.
2. \`node scripts/tracker.mjs\` to see the board. Your item is the In progress line in
   \`docu/00-overview/tracker/${workstream}.md\` (the tracker wins over this snapshot):
${itemLines}
3. Read \`docu/00-overview/road-to-production.md\` for the item's scope, size and acceptance check, and
   \`docu/00-overview/program-tracker.md\` for the tracking rules.
4. Tell the user in one line which item you are on and what you will do first, then start.

## While working

- Follow \`.claude/rules/\` (git-workflow, architecture, fiori-ux, performance, sap-backend, frontend-testing).
- Edit only \`tracker/${workstream}.md\` among the tracker files; new ideas, risks and follow-ups go to
  \`docu/00-overview/tracker/ideas.md\` immediately.
- Shared contracts (CDS shapes, ObjectKeyJson, shared React components, fioriService.js) land on \`main\` first;
  pick up others' changes with \`git merge --no-edit origin/main\`.
- ABAP changes start and are merged in \`../../a4h_2023_zado\` and are smoke-tested on RD1 DEV/100. \`abap/src\` is a reference copy: update the two contract-test files (dispatcher class, smoke report) only in a PR that changes a step type or key shape; wholesale re-sync at milestones.
- \`node_modules\` may be junction-linked to the primary checkout: run \`npm ci\` here the moment this branch changes
  dependencies.

## Finish

Tests green (\`cd code && npm test\`; \`cd code/app/adops-client && npm test && npm run lint\`), browser check on port
${slot.client} when the change is visible, tracker item moved to Accomplished with \`PR #n, date\`, Daily log line
written, push the branch, then give the user the PR title and description (summary, tests, shared contracts,
workstream + item ID, merge order). Never push to \`main\`.
`;
}

function writeSessionBrief(dir, workstream, branch, slot) {
  fs.writeFileSync(path.join(dir, 'CLAUDE.local.md'), sessionBrief(dir, workstream, branch, slot));
  log(`wrote ${path.join(dir, 'CLAUDE.local.md')} (session brief)`);
}

// Regenerate the session brief for one or all existing worktrees. Works from
// the primary checkout or from inside a worktree.
function sync(workstream) {
  const names = workstream ? [workstream] : Object.keys(SLOTS);
  let count = 0;
  for (const name of names) {
    const dir = worktreePath(name);
    if (!fs.existsSync(dir)) { if (workstream) fail(`${dir} does not exist.`); continue; }
    const branch = git(['branch', '--show-current'], { cwd: dir, allowFailure: true }) || '(detached)';
    writeSessionBrief(dir, name, branch, slotFor(name));
    count += 1;
  }
  if (!count) log('no worktrees found to sync');
}

function ensureMainCheckout() {
  const gitDir = git(['rev-parse', '--git-dir']);
  if (gitDir !== '.git' && !gitDir.endsWith(`${path.sep}.git`) && !gitDir.endsWith('/.git')) {
    fail(`Run this from the primary checkout (${repoRoot}), not from a linked worktree.`);
  }
}

function freshMain() {
  git(['fetch', '--prune', 'origin']);
  return git(['rev-parse', '--short', 'origin/main']);
}

function checkoutFreshBranch(dir, branch) {
  git(['checkout', '--detach', 'origin/main'], { cwd: dir });
  git(['checkout', '-b', branch], { cwd: dir });
}

function linkOrInstall(dir, { linkModules, install }) {
  const logFile = path.join(dir, '.worktree-setup.log');
  const targets = [
    { rel: 'code', src: path.join(repoRoot, 'code', 'node_modules') },
    { rel: path.join('code', 'app', 'adops-client'), src: path.join(repoRoot, 'code', 'app', 'adops-client', 'node_modules') }
  ];
  for (const target of targets) {
    const pkgDir = path.join(dir, target.rel);
    const modules = path.join(pkgDir, 'node_modules');
    if (fs.existsSync(modules)) continue;
    if (linkModules) {
      if (!fs.existsSync(target.src)) fail(`--link-modules: ${target.src} does not exist; run npm install in the main checkout first.`);
      fs.symlinkSync(target.src, modules, 'junction');
      log(`linked ${path.relative(dir, modules)} -> main checkout (same lockfile assumed; run npm ci here if this branch changes dependencies)`);
    } else if (install) {
      run('npm', ['ci', '--no-audit', '--no-fund'], pkgDir, logFile);
    }
  }
  return logFile;
}

// Same command as `npm run db:init:sqlite`, invoked directly so a worktree
// cut from an older main (without that script) still gets its database.
function initDatabase(dir, logFile) {
  const dbFile = path.join(dir, 'code', 'db.sqlite');
  if (fs.existsSync(dbFile)) return;
  run('npx', ['cds', 'deploy', '--profile', 'development'], path.join(dir, 'code', 'srv'), logFile,
    { NODE_ENV: 'development', CDS_ENV: 'development' });
}

function add(workstream, branch, flags) {
  ensureMainCheckout();
  if (!branch) fail('Usage: add <workstream> <branch>');
  const slot = slotFor(workstream);
  const dir = worktreePath(workstream);
  if (fs.existsSync(dir)) fail(`${dir} already exists - use "next" to re-point it or "remove" first.`);
  const head = freshMain();
  fs.mkdirSync(worktreesRoot, { recursive: true });
  log(`adding worktree ${dir} from origin/main (${head}) on branch ${branch}`);
  git(['worktree', 'add', '--detach', dir, 'origin/main']);
  git(['checkout', '-b', branch], { cwd: dir });
  fs.mkdirSync(path.join(dir, '.claude'), { recursive: true });
  fs.writeFileSync(path.join(dir, '.claude', 'launch.json'), launchJson(slot));
  writeSessionBrief(dir, workstream, branch, slot);
  const logFile = linkOrInstall(dir, flags);
  if (flags.install || flags.linkModules) initDatabase(dir, logFile);
  summary(workstream, dir, branch, slot);
}

function next(workstream, branch) {
  ensureMainCheckout();
  if (!branch) fail('Usage: next <workstream> <branch>');
  const dir = worktreePath(workstream);
  if (!fs.existsSync(dir)) fail(`${dir} does not exist - use "add".`);
  const status = git(['status', '--porcelain'], { cwd: dir });
  const dirty = status.split('\n').filter((line) => line && !line.includes('.claude/launch.json'));
  if (dirty.length) fail(`worktree has uncommitted changes:\n${dirty.join('\n')}\nCommit or stash them first.`);
  const head = freshMain();
  log(`re-pointing ${dir} at origin/main (${head}) on new branch ${branch}`);
  checkoutFreshBranch(dir, branch);
  writeSessionBrief(dir, workstream, branch, slotFor(workstream));
  const logFile = path.join(dir, '.worktree-setup.log');
  run('npm', ['run', 'db:refresh:sqlite'], path.join(dir, 'code'), logFile);
  summary(workstream, dir, branch, slotFor(workstream));
}

function list() {
  console.log(git(['worktree', 'list']));
  console.log('');
  console.log('slot        CAP    client  path');
  for (const [name, slot] of Object.entries(SLOTS)) {
    const dir = worktreePath(name);
    const branch = fs.existsSync(dir) ? git(['branch', '--show-current'], { cwd: dir, allowFailure: true }) || '(detached)' : '-';
    console.log(`${name.padEnd(11)} ${String(slot.cap).padEnd(6)} ${String(slot.client).padEnd(7)} ${fs.existsSync(dir) ? `${dir}  [${branch}]` : '(not created)'}`);
  }
}

function remove(workstream) {
  ensureMainCheckout();
  const dir = worktreePath(workstream);
  if (!fs.existsSync(dir)) fail(`${dir} does not exist.`);
  const status = git(['status', '--porcelain'], { cwd: dir });
  const dirty = status.split('\n').filter((line) => line && !line.includes('.claude/launch.json') && !line.includes('.worktree-setup.log'));
  if (dirty.length) fail(`worktree has uncommitted changes:\n${dirty.join('\n')}\nCommit, push or discard them first (git worktree remove --force to discard).`);
  git(['worktree', 'remove', '--force', dir]);
  git(['worktree', 'prune']);
  log(`removed ${dir}. Branches are kept; delete merged ones with git branch -d.`);
}

function summary(workstream, dir, branch, slot) {
  console.log('');
  log(`ready: ${workstream}`);
  console.log(`  path     ${dir}`);
  console.log(`  branch   ${branch}`);
  console.log(`  CAP      http://localhost:${slot.cap}   (preview_start "adops-cap" in this worktree)`);
  console.log(`  client   http://localhost:${slot.client}   (preview_start "adops-client")`);
  console.log('  next     open a Claude Code session in that folder, or: cd there && code .');
  console.log('  finish   push, open the PR, then: node scripts/worktree.mjs next <workstream> <next-branch>');
}

const [command, workstream, branch, ...rest] = process.argv.slice(2);
const flags = {
  linkModules: rest.includes('--link-modules') || branch === '--link-modules',
  install: !rest.includes('--no-install')
};

switch (command) {
  case 'add': add(workstream, branch, flags); break;
  case 'next': next(workstream, branch); break;
  case 'list': list(); break;
  case 'sync': sync(workstream); break;
  case 'remove': remove(workstream); break;
  default:
    console.log('Usage:');
    console.log('  node scripts/worktree.mjs add <workstream> <branch> [--link-modules] [--no-install]');
    console.log('  node scripts/worktree.mjs next <workstream> <branch>');
    console.log('  node scripts/worktree.mjs sync [<workstream>]   # regenerate CLAUDE.local.md session briefs');
    console.log('  node scripts/worktree.mjs list');
    console.log('  node scripts/worktree.mjs remove <workstream>');
    console.log(`Workstreams: ${Object.keys(SLOTS).join(', ')}`);
    process.exit(command ? 1 : 0);
}
